practical_exam/blogs/urls.py
from django.conf.urls import url

from .views import blog_index, blog_post_detail, blog_section_list, contact_us

urlpatterns = [
    url(r'^$', blog_index, name="home"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        blog_post_detail,
        name="blog_post"),
    url(r'^post/(?P<post_pk>\d+)/$', blog_post_detail, name="blog_post_pk"),
#    url(r'^(?P<section_slug>[-\w]+)/$', blog_section_list, name="blog_section"),
    url(r'^contact_us/$', contact_us, name="contact-us"),
]

practical_exam/practical_exam/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth import views as auth_views


from django.contrib import admin

urlpatterns = [
	url(r'^login/$', auth_views.login, {'template_name': 'blogs/blog_login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'blogs/blog_logout.html'}, name='logout'),
    url(r"^admin/", include(admin.site.urls)),
    url(r"", include("blogs.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

practical_exam/blogs/models.py
# -*- coding: utf8 -*-
import json
import urllib2

from datetime import datetime

from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django import forms
from django.contrib.sites.models import Site

try:
    import twitter
except ImportError:
    twitter = None

from blogs.managers import PostManager
from blogs.settings import MARKUP_CHOICES
from blogs.utils import can_tweet


class Section(models.Model):
    name = models.CharField(max_length=140)
    slug = models.SlugField()

    def __unicode__(self):
        return self.name


class Post(models.Model):
    section = models.ForeignKey(Section, related_name="posts")
    title = models.CharField(max_length=90)
    slug = models.SlugField()
    author = models.ForeignKey(User, related_name="posts")
    markup = models.CharField(max_length=25, choices=MARKUP_CHOICES)
    teaser_html = models.TextField(editable=False)
    content_html = models.TextField(editable=False)
    tweet_text = models.CharField(max_length=140, editable=False)
    # when first revision was created
    created = models.DateTimeField(default=datetime.now, editable=False)
    # when last revision was create (even if not published)
    updated = models.DateTimeField(null=True, blank=True, editable=False)
    # when last published
    published = models.DateTimeField(null=True, blank=True, editable=False)
    view_count = models.IntegerField(default=0, editable=False)

    def rev(self, rev_id):
        return self.revisions.get(pk=rev_id)

    def current(self):
        "the currently visible (latest published) revision"
        return self.revisions.exclude(published=None).order_by("-published")[0]

    def latest(self):
        "the latest modified (even if not published) revision"
        try:
            return self.revisions.order_by("-updated")[0]
        except IndexError:
            return None

    class Meta:
        ordering = ("-published",)
        get_latest_by = "published"

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def as_tweet(self):
        if not self.tweet_text:
            current_site = Site.objects.get_current()
            api_url = "http://api.tr.im/api/trim_url.json"
            u = urllib2.urlopen("%s?url=http://%s%s" % (
                api_url,
                current_site.domain,
                self.get_absolute_url(),
            ))
            result = json.loads(u.read())
            self.tweet_text = u"%s %s — %s" % (
                settings.TWITTER_TWEET_PREFIX,
                self.title,
                result["url"],
            )
        return self.tweet_text

    def tweet(self):
        if can_tweet():
            account = twitter.Api(
                username=settings.TWITTER_USERNAME,
                password=settings.TWITTER_PASSWORD,
            )
            account.PostUpdate(self.as_tweet())
        else:
            err_msg = (
                "Unable to send tweet due to either "
                "missing python-twitter or required settings."
            )
            raise ImproperlyConfigured(err_msg)

    def save(self, **kwargs):
        self.updated_at = datetime.now()
        super(Post, self).save(**kwargs)

    def get_absolute_url(self):
        if self.published:
            name = "blog_post"
            kwargs = {
                "year": self.published.strftime("%Y"),
                "month": self.published.strftime("%m"),
                "day": self.published.strftime("%d"),
                "slug": self.slug,
            }
        else:
            name = "blog_post_pk"
            kwargs = {
                "post_pk": self.pk,
            }
        return reverse(name, kwargs=kwargs)

    def inc_views(self):
        self.view_count += 1
        self.save()
        self.current().inc_views()


class Revision(models.Model):

    post = models.ForeignKey(Post, related_name="revisions")

    title = models.CharField(max_length=90)
    teaser = models.TextField()

    content = models.TextField()

    author = models.ForeignKey(User, related_name="revisions")

    updated = models.DateTimeField(default=datetime.now)
    published = models.DateTimeField(null=True, blank=True)

    view_count = models.IntegerField(default=0, editable=False)

    def __unicode__(self):
        return 'Revision %s for %s' % (self.updated.strftime('%Y%m%d-%H%M'), self.post.slug)

    def inc_views(self):
        self.view_count += 1
        self.save()


class Image(models.Model):

    post = models.ForeignKey(Post, related_name="images")

    image_path = models.ImageField(upload_to="images/%Y/%m/%d")
    url = models.CharField(max_length=150, blank=True)

    timestamp = models.DateTimeField(default=datetime.now, editable=False)

    def __unicode__(self):
        if self.pk is not None:
            return "{{ %d }}" % self.pk
        else:
            return "deleted image"


class FeedHit(models.Model):

    request_data = models.TextField()
    created = models.DateTimeField(default=datetime.now)

class ContactUs(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=150, blank=True)
    message = models.CharField(max_length=150, blank=True)

practical_exam/blogs/forms.py
from datetime import datetime

from django import forms
from django.utils.functional import curry

from blogs.models import Post, Revision
from blogs.utils import can_tweet, load_path_attr
from blogs.settings import MARKUP_CHOICE_MAP


class AdminPostForm(forms.ModelForm):

    title = forms.CharField(
        max_length=90,
        widget=forms.TextInput(attrs={"style": "width: 50%;"},),
    )
    slug = forms.CharField(
        widget=forms.TextInput(attrs={"style": "width: 50%;"},)
    )
    teaser = forms.CharField(
        widget=forms.Textarea(attrs={"style": "width: 80%;"},),
    )
    content = forms.CharField(
        widget=forms.Textarea(attrs={"style": "width: 80%; height: 300px;"},)
    )
    publish = forms.BooleanField(
        required=False,
        help_text=u"Checking this will publish this articles on the site",
    )

    if can_tweet():
        tweet = forms.BooleanField(
            required=False,
            help_text=u"Checking this will send out a tweet for this post",
        )

    class Meta:
        model = Post
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AdminPostForm, self).__init__(*args, **kwargs)

        post = self.instance

        # grab the latest revision of the Post instance
        latest_revision = post.latest()

        if latest_revision:
            # set initial data from the latest revision
            self.fields["teaser"].initial = latest_revision.teaser
            self.fields["content"].initial = latest_revision.content

            # @@@ can a post be unpublished then re-published? should be pulled
            # from latest revision maybe?
            self.fields["publish"].initial = bool(post.published)

    def save(self):
        post = super(AdminPostForm, self).save(commit=False)

        if post.pk is None:
            if self.cleaned_data["publish"]:
                post.published = datetime.now()
        else:
            if Post.objects.filter(pk=post.pk, published=None).count():
                if self.cleaned_data["publish"]:
                    post.published = datetime.now()

        path_ = load_path_attr(MARKUP_CHOICE_MAP[self.cleaned_data["markup"]]["parser"])
        render_func = curry(path_)

        post.teaser_html = render_func(self.cleaned_data["teaser"])
        post.content_html = render_func(self.cleaned_data["content"])
        post.updated = datetime.now()
        post.save()

        r = Revision()
        r.post = post
        r.title = post.title
        r.teaser = self.cleaned_data["teaser"]
        r.content = self.cleaned_data["content"]
        r.author = post.author
        r.updated = post.updated
        r.published = post.published
        r.save()

        if can_tweet() and self.cleaned_data["tweet"]:
            post.tweet()

        return post

practical_exam/blogs/views.py
import json

from datetime import datetime

from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404, render
from django.template import RequestContext
from django.template.loader import render_to_string

from blogs.models import FeedHit, Post, Section
from blogs.settings import ALL_SECTION_NAME
from blogs.signals import post_viewed

from django.contrib.auth.decorators import login_required


@login_required(login_url='/login/')
def blog_index(request):

    posts = Post.objects.current()

    return render(request, "blogs/blog_list.html", {
        "posts": posts,
    })


@login_required(login_url='/login/')
def blog_section_list(request, section_slug):

    section = get_object_or_404(Section, slug=section_slug)
    posts = section.posts.all()
    return render_to_response(
        "blogs/blog_section_list.html",
        {"section_slug": section_slug,
         "section_name": section.name,
         "posts": posts},
        context_instance=RequestContext(request))


@login_required(login_url='/login/')
def blog_post_detail(request, **kwargs):

    if "post_pk" in kwargs:
        if request.user.is_authenticated() and request.user.is_staff:
            queryset = Post.objects.all()
            post = get_object_or_404(queryset, pk=kwargs["post_pk"])
        else:
            raise Http404()
    else:
        queryset = Post.objects.current()
        queryset = queryset.filter(
            published__year=int(kwargs["year"]),
            published__month=int(kwargs["month"]),
            published__day=int(kwargs["day"]),
        )
        post = get_object_or_404(queryset, slug=kwargs["slug"])
        post_viewed.send(sender=post, post=post, request=request)

    return render_to_response("blogs/blog_post.html", {
        "post": post,
    }, context_instance=RequestContext(request))


@login_required(login_url='/login/')
def serialize_request(request):
    data = {
        "path": request.path,
        "META": {
            "QUERY_STRING": request.META.get("QUERY_STRING"),
            "REMOTE_ADDR": request.META.get("REMOTE_ADDR"),
        }
    }
    for key in request.META:
        if key.startswith("HTTP"):
            data["META"][key] = request.META[key]
    return json.dumps(data)


@login_required(login_url='/login/')
def blog_feed(request, section=None):

    section = get_object_or_404(Section, slug=section)
    posts = Post.objects.filter(section=section)

    if section is None:
        section = Section.objects.values_list('name', flat=True).order_by('name')

    current_site = Site.objects.get_current()

    feed_title = "%s Blog: %s" % (current_site.name, section[0].upper() + section[1:])

    blog_url = "http://%s%s" % (current_site.domain, reverse("blog"))

    url_name, kwargs = "blog_feed", {"section": section}
    feed_url = "http://%s%s" % (current_site.domain, reverse(url_name, kwargs=kwargs))

    if posts:
        feed_updated = posts[0].published
    else:
        feed_updated = datetime(2009, 8, 1, 0, 0, 0)

    # create a feed hit
    hit = FeedHit()
    hit.request_data = serialize_request(request)
    hit.save()

    atom = render_to_string("blogs/atom_feed.xml", {
        "feed_id": feed_url,
        "feed_title": feed_title,
        "blog_url": blog_url,
        "feed_url": feed_url,
        "feed_updated": feed_updated,
        "entries": posts,
        "current_site": current_site,
    })
    return HttpResponse(atom, mimetype="application/atom+xml")

@login_required(login_url='/login/')
def contact_us(request):
    posts = Post.objects.current()

    return render(request, "blogs/blog_contact_us.html", {
        "posts": posts,
    })

def post_new(request):
    form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

practical_exam/practical_exam/templates/blogs/blog_base.html
{% extends "site_base.html" %}

{% block body_class %}blog{% endblock %}


{% block body %}
    <div class="row blog-container">
        <div class="col-md-3 sidebar">
            {% block sidebar %}
                <h1>
                    <a href="#">About the blog</a>
                </h1>
                <p class="lead">
                    This is where you can list your bio, add links
                    etc., by editing the <code>blogs/blog_base.html</code>
                    template.
            {% endblock %}
        </div>
        <div class="col-md-8 blog-content">
            {% block content %}{% endblock %}
        </div>
    </div>
{% endblock %}

practical_exam/practical_exam/templates/blogs/blog_contact_us.html
{% extends "blogs/blog_base.html" %}

{% load staticfiles %}

{% block head_title %}{{ SITE_NAME }}{% endblock %}

{% block content %}
        <div class="container">

                <div class="contact">
                    <form action="/postnew/" method="post">
                        {% csrf_token %}
                        {{ form }}
                        <div class="form-group">
                            <label for="email">Email address:</label>
                            <input type="email" class="form-control" id="email">
                        </div>
                        <div class="form-group">
                            <label for="subject">Subject:</label>
                            <input type="text" class="form-control" id="subject">
                        </div>
                        <div class="form-group">
                            <label for="message">Message:</label>
                            <textarea class="form-control" rows="5" id="message"></textarea>
                        </div> 
                        <button type="submit" class="btn btn-default">Submit</button>


                </div>    
        </div>
{% endblock %}

practical_exam/practical_exam/templates/blogs/blog_list.html
{% extends "blogs/blog_base.html" %}

{% block head_title %}{{ SITE_NAME }}{% endblock %}

{% block content %}
    {% if posts %}
        <div class="post-list">
            {% for post in posts %}
                <div class="post">
                    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                    {% include "blogs/dateline.html" %}

                    <div class="teaser">{{ post.teaser_html|safe }}</div>
                    <p class="more"><a href="{{ post.get_absolute_url }}" class="post-link">read more...</a></p>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No blog posts have been published.</p>
        
    {% endif %}
{% endblock %}

practical_exam/practical_exam/templates/blogs/blog_login.html
{% extends 'blogs/blog_base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

practical_exam/practical_exam/templates/blogs/blog_logout.html
{% extends 'blogs/blog_base.html' %}

{% block title %}Logout{% endblock %}

{% block content %}
  <h2>Logout</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Logout</button>
  </form>
{% endblock %}

practical_exam/practical_exam/templates/blogs/blog_post.html
{% extends "blogs/blog_base.html" %}

{% block head_title %}{{ post.title }} &mdash; {{ SITE_NAME }}{% endblock %}

{% block extra_head %}
    <meta name="description" content="{{ post.teaser_html|striptags }}">
    <meta name="og:title" content="{{ post.title }}">
    <meta name="og:description" content="{{ post.teaser_html|striptags }}">
{% endblock %}

{% block content %}
    <div class="post-detail">
        <div class="post">
            <h1>{{ post.title }}</h1>
            {% include "blogs/dateline_stale.html" %}

            <div class="teaser">{{ post.teaser_html|safe }}</div>

            <div class="content">{{ post.content_html|safe }}</div>

            <div class="twitter-button">
                <a href="https://twitter.com/share" class="twitter-share-button" data-via="">Tweet</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            </div>
        </div>
    </div>
{% endblock %}

practical_exam/practical_exam/templates/blogs/blog_section_list.html
{% extends "blogs/blog_base.html" %}


{% block head_title %}{{ SITE_NAME }} ({{ section_name }}){% endblock %}

{% block content %}
    {% if posts %}
        <div class="post-list">
            {% for post in posts %}
                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                {% include "blogs/dateline.html" %}
                <div class="teaser">{{ post.teaser_html|safe }}</div>
                <p class="more"><a href="{{ post.get_absolute_url }}" class="post-link">read more...</a></p>
            {% endfor %}
        </div>
    {% else %}
        <p>No blog posts have been published in this section.</p>
    {% endif %}
{% endblock %}

practical_exam/practical_exam/templates/blogs/dateline.html
<p class="post_dateline">
    <span class="date">{% if post.published %}{{ post.published|date:"jS F Y" }}{% else %}Not published yet{% endif %}</span>
    <br />
    by <span class="author"><a href="http://twitter.com/{{ post.author.username }}" title="@{{ post.author.username }}">{{ post.author.get_full_name }}</a></span> in
    <a href="{% url "blog_section" post.section.slug %}"><span class="section">{{ post.get_section_display|capfirst }}</span></a>
</p>

practical_exam/practical_exam/templates/blogs/dateline_stale.html
<p class="post_dateline">
    {% if not post.stale %}
        <span class="date">{% if post.published %}{{ post.published|date:"jS F Y" }}{% else %}Not published yet{% endif %}</span>
        <br />
    {% endif %}
    by <span class="author"><a href="http://twitter.com/{{ post.author.username }}" title="@{{ post.author.username }}">{{ post.author.get_full_name }}</a></span> in
    <a href="{% url "blog_section" post.section.slug %}"><span class="section">{{ post.get_section_display|capfirst }}</span></a>
</p>